include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-dhcp-comment
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for DHCP Chinese Comment Enhancer
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
